# Generated by Django 5.1.1 on 2024-09-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('image', models.URLField()),
                ('price', models.FloatField()),
                ('availability', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=20)),
                ('voltage', models.CharField(max_length=20)),
            ],
        ),
    ]
